image:
  size: 64

  mean:
    - 0.5
  std:
    - 0.5
  
  
  channel: 1

  batch_size: 32

data:
  dir: cat_dog

input:
  batch_size: 8
  z_dim: 100

train:
  num_epochs: 200

optimizer:
  algorithm: Adam
  g_lr: 0.0001
  d_lr: 0.0004
  beta1: 0.0
  beta2: 0.9
